# chunhui2001/centos_7_dev:haproxy_base
# Version 0.0.1
FROM chunhui2001/centos_7_dev:basic
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

#ENV REFRESHED_AT 2017-11-21


RUN yum install -y epel-release haproxy
RUN yum install -y certbot
#RUN service haproxy stop





