# chenrj/centos_7_dev:haproxy_base
# Version 0.0.1
FROM chenrj/centos_7_dev:basic
MAINTAINER chenrj "790099746@qq.com"

#ENV REFRESHED_AT 2017-11-21


RUN yum install -y epel-release haproxy
RUN yum install -y certbot
#RUN service haproxy stop





