# chunhui2001/ubuntu_1610_dev:haproxy_base
# Version 0.0.1
FROM chunhui2001/ubuntu_1610_dev:zh-CN
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

ENV REFRESHED_AT 2017-11-10

RUN apt-get install -y haproxy


