
wget  Python-3.3.0.tgz
tar -zxf  Python-3.3.0.tgz && cd  Python-3.3.0 && ./configure && make && make install
virtualenv  --no-setuptools -p /usr/local/bin/python3.3 py3env
source py3env/bin/activate
$ python
$ pip install httplib2


### HAProxy plugin for Let's Encrypt's Certbot
https://github.com/greenhost/certbot-haproxy

### How To Secure (Certbot) HAProxy with Let's Encrypt on CentOS 7
https://poweruphosting.com/blog/secure-certbot-haproxy/

### How To Secure HAProxy with Let's Encrypt on CentOS 7
https://www.digitalocean.com/community/tutorials/how-to-secure-haproxy-with-let-s-encrypt-on-centos-7

docker run -d -v /root/app/letsencrypt:/opt/letsencrypt -v /root/app/letsencrypt_etc:/etc/letsencrypt -p 9000:80 chunhui2001/centos_7_dev:nginx_1.9.15

### How To Secure Nginx with Let's Encrypt on Ubuntu 16.04
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

###  letsencrypt在nginx下的配置
https://segmentfault.com/a/1190000005142228

###  CentOS 6.5下利用Docker使用Letsencrypt
https://segmentfault.com/a/1190000007238745




